-- setmode.lua

Logger = require('helpers/Logger')
Var = require('helpers/Variables')
Config = {}
Cyberpunk = require('helpers/Cyberpunk')

function Config.SetMode()
	Logger.info('Configuring mode for', Var.settings.mode)

	if Var.settings.mode == 'Unknown' then
		if not Cyberpunk.GetOption('/graphics/raytracing', 'RayTracing') then
			Var.settings.mode = Var.mode.RASTER
			return
		end

		if not Cyberpunk.GetOption('/graphics/raytracing', 'RayTracedPathTracing') then
			Var.settings.mode = Var.mode.RTOnly
			return
		end

		Var.settings.mode = Var.mode.PT21
	end

	if Var.settings.mode == Var.mode.RASTER then
		LoadIni('config/raster.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', false)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '0')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', false)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', false)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', false)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', false)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', false)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', false)
		-- Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '100.0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '1')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', false)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.025')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '1.0')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.15')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', false)
		Cyberpunk.SetOption('Editor/SHARC', 'Enable', false)
		return
	end

	if Var.settings.mode == Var.mode.RTOnly then
		LoadIni('config/rt.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '1')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', true)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		-- Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '100.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', true)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', false)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.025')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '1.0')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.35')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', false)
		Cyberpunk.SetOption('Editor/SHARC', 'Enable', false)
		return
	end

	if Var.settings.mode == Var.mode.RT_PT then
		LoadIni('config/rtpt.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', false)
		-- Cyberpunk.SetOption('Developer/FeatureToggles', 'DistantGI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'EnableNRD', true)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '1')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', true)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '70.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', true)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', true)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', false)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', false)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.05')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '2.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '0')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', '24.0')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.45')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'NumEnvMapSamples', '8')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.15')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', true)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', true)
		return
	end

	if Var.settings.mode == Var.mode.VANILLA then
		LoadIni('config/vanilla.ini', true)

		-- Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		-- Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', true)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', true)
		Cyberpunk.SetOption('RayTracing', 'RayNormalOffset', '0.01')
		Cyberpunk.SetOption('RayTracing', 'RayViewOffset', '0.005')
		Cyberpunk.SetOption('Editor/RTXDI', 'EmissiveShadowRayOffset', '0.01')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableLocalLightImportanceSampling', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '1')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.5')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', true)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', true)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '100.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', true)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', true)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '1')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '1')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', true)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', false)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', false)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '3')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '3')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '3')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '3')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.025')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '1.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '32')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BoilingFilterStrength', '0.4')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', '32.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '8')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '8')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '1')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', '32.0')
		Cyberpunk.SetOption('Editor/RTXDI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.5')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'NumEnvMapSamples', '8')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.1')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', false)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', true)
		return
	end

	if Var.settings.mode == Var.mode.PT16 then
		LoadIni('config/pt.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', true)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', true)
		Cyberpunk.SetOption('RayTracing', 'RayNormalOffset', '0.015')
		Cyberpunk.SetOption('RayTracing', 'RayViewOffset', '0.005')
		Cyberpunk.SetOption('Editor/RTXDI', 'EmissiveShadowRayOffset', '0.015')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableLocalLightImportanceSampling', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '0')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', true)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '70.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', true)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', true)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', true)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', true)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', true)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.1')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '2.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '0')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_DI or Var.config.BASE_SPATIAL_DI)
		Cyberpunk.SetOption('Editor/RTXDI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.45')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'NumEnvMapSamples', '24')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.4')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', true)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', true)

		Cron.After(1.0, function()
			Cyberpunk.SetOption('RayTracing', 'EnableShadowCascades', false)
		end)
		return
	end

	if Var.settings.mode == Var.mode.PT20 then
		LoadIni('config/pt_20.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', true)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', true)
		Cyberpunk.SetOption('RayTracing', 'RayNormalOffset', '0.015')
		Cyberpunk.SetOption('RayTracing', 'RayViewOffset', '0.005')
		Cyberpunk.SetOption('Editor/RTXDI', 'EmissiveShadowRayOffset', '0.015')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableLocalLightImportanceSampling', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.1')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '2.0')
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '0')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', true)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '70.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', true)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', false)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', false)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', false)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '0')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_DI or Var.config.BASE_SPATIAL_DI)
		Cyberpunk.SetOption('Editor/RTXDI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.45')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'NumEnvMapSamples', '24')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.4')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', true)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', true)

		Cron.After(1.0, function()
			Cyberpunk.SetOption('RayTracing', 'EnableShadowCascades', false)
		end)
		return
	end

	if Var.settings.mode == Var.mode.PT21 then
		LoadIni('config/pt.ini', true)

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', true)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', false)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', false)

		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', false)
		Cyberpunk.SetOption('RayTracing', 'RayNormalOffset', '0.015')
		Cyberpunk.SetOption('RayTracing', 'RayViewOffset', '0.005')
		Cyberpunk.SetOption('Editor/RTXDI', 'EmissiveShadowRayOffset', '0.015')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableLocalLightImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '0')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', false)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '100.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', false)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', false)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', false)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', false)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.1')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '2.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '48')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_GI or Var.config.BASE_SPATIAL_GI)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '4')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '1')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '1')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_DI or Var.config.BASE_SPATIAL_DI)
		Cyberpunk.SetOption('Editor/RTXDI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'NumEnvMapSamples', '24')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)		-- WAS true
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'UseAOOnEyes', false)
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.4')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', true)
		Cyberpunk.SetOption('Editor/PathTracing', 'UseSSRFallback', true)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', false)

		Cron.After(1.0, function()
			Cyberpunk.SetOption('RayTracing', 'EnableShadowCascades', false)
		end)
		return
	end

	if Var.settings.mode == Var.mode.HYBRID or Var.settings.mode == Var.mode.PTNEXT then
		local ptNext = (Var.settings.mode == Var.mode.PTNEXT)
		
		if ptNext then
			LoadIni('config/pt_next.ini', true)
		else
			LoadIni('config/pt_hybrid.ini', true)
		end

		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracing', true)
		Cyberpunk.SetOption('/graphics/raytracing', 'RayTracedPathTracing', true)
		Cyberpunk.SetOption('Editor/ReGIR', 'Enable', true)
		Cyberpunk.SetOption('Editor/ReGIR', 'UseForDI', ptNext and true or false)
		Cyberpunk.SetOption('Editor/ReGIR', 'LightSlotsCount', ptNext and '256' or '128')

		Cyberpunk.SetOption('Developer/FeatureToggles', 'PathTracingForPhotoMode', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'RTXDI', true)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpaceReflection', false)
		Cyberpunk.SetOption('Developer/FeatureToggles', 'ScreenSpacePlanarReflection', false)
		Cyberpunk.SetOption('Rendering', 'AllowRTXDIRejitter', false)
		Cyberpunk.SetOption('Rendering', 'AllowRayTracedReferenceRejitter', false)
		Cyberpunk.SetOption('RayTracing', 'RayNormalOffset', '0.015')
		Cyberpunk.SetOption('RayTracing', 'RayViewOffset', '0.005')
		Cyberpunk.SetOption('Editor/RTXDI', 'EmissiveShadowRayOffset', '0.015')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableLocalLightImportanceSampling', false)
		Cyberpunk.SetOption('RayTracing', 'AmbientOcclusionRayNumber', '0')
		Cyberpunk.SetOption('RayTracing', 'SunAngularSize', '0.25')
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableLocalShadow', true)
		Cyberpunk.SetOption('RayTracing', 'EnableTransparentReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableDiffuseIllumination', true)
		Cyberpunk.SetOption('RayTracing', 'EnableAmbientOcclusion', false)
		Cyberpunk.SetOption('RayTracing', 'EnableReflection', true)
		Cyberpunk.SetOption('RayTracing', 'EnableShadowOptimizations', true)
		Cyberpunk.SetOption('RayTracing', 'EnableGlobalIllumination', false)
		Cyberpunk.SetOption('RayTracing', 'EnableImportanceSampling', true)
		Cyberpunk.SetOption('RayTracing', 'ForceShadowLODBiasUsage', false)
		Cyberpunk.SetOption('RayTracing/Debug', 'EnableVisibilityCheck', false)
		Cyberpunk.SetOption('RayTracing/Collector', 'LocalShadowCullingRadius', '100.0')
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableFixed', false)
		Cyberpunk.SetOption('RayTracing/Reference', 'EnableRIS', true)
		Cyberpunk.SetOption('RayTracing/Reflection', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Reflection', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/Diffuse', 'EnableHalfResolutionTracing', '0')
		Cyberpunk.SetOption('RayTracing/Diffuse', 'AdaptiveSampling', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForDirectRadiance', false)
		Cyberpunk.SetOption('RayTracing/NRD', 'UseReblurForIndirectRadiance', false)
		Cyberpunk.SetOption('Editor/Denoising/ReBLUR/Direct', 'ReferenceAccumulation', false)
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Direct/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Specular', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Editor/Denoising/ReLAX/Indirect/Diffuse', 'MaxFastAccumulatedFrameNum', '128')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'Enable', true)
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'VarianceCutoff', '0.1')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'MotionFactor', '0.75')
		Cyberpunk.SetOption('Rendering/VariableRateShading', 'ScreenEdgeFactor', '2.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'Enable', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFused', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableFallbackSampling', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxReservoirAge', '48')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'EnableBoilingFilter', false)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_GI or Var.config.BASE_SPATIAL_GI)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseSpatialRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'UseTemporalRGS', true)
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'MaxHistoryLength', '8')		-- WAS 1
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'TargetHistoryLength', '4')	-- WAS 1
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'BiasCorrectionMode', '1')
		Cyberpunk.SetOption('Editor/ReSTIRGI', 'PermutationSamplingMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'UseCustomDenoiser', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableRTXDIDenoising', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableGradients', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'SpatialSamplingRadius', Var.settings.boilingFixBoost and Var.config.BOOSTED_SPATIAL_DI or Var.config.BASE_SPATIAL_DI)
		Cyberpunk.SetOption('Editor/RTXDI', 'PermutationSamplingMode', '3')
		Cyberpunk.SetOption('Editor/RTXDI', 'InitialCandidatesInTemporal', true)
		Cyberpunk.SetOption('Editor/RTXDI', 'BoilingFilterStrength', '0.0')
		Cyberpunk.SetOption('Editor/RTXDI', 'BiasCorrectionMode', '2')
		Cyberpunk.SetOption('Editor/RTXDI', 'EnableApproximateTargetPDF', false)
		Cyberpunk.SetOption('Editor/RTXDI', 'ForcedShadowLightSourceRadius', '0.1')
		Cyberpunk.SetOption('Editor/Characters/Eyes', 'DiffuseBoost', '0.0')
		Cyberpunk.SetOption('Editor/PathTracing', 'UseScreenSpaceData', true)
		Cyberpunk.SetOption('Editor/PathTracing', 'UseSSRFallback', true)
		Cyberpunk.SetOption('Editor/Denoising/NRD', 'EnableScalingCompensation', false)

		Cron.After(1.0, function()
			Cyberpunk.SetOption('RayTracing', 'EnableShadowCascades', false)
		end)
		return
	end
end

return Config
