-- helpers/Variables.lua

local Var = {
	confirmationRequired = false,
	configFile = 'UltraPlusConfig.ini',
	window = {
		open            = false,
		scale           = 1.0,
		startX          = 0,
		startY          = 0,
		finishX         = 0,
		finishY         = 0,
		initialWidth    = 0,
		initialHeight   = 0,
		intSize         = 100,
		floatSize       = 100,
		filterText      = '',
	},
	mode = {
		PT16    = 'PT16',
		PT20    = 'PT20',
		PT21    = 'PT21',
		PTNEXT  = 'PTNextV2',
		HYBRID  = 'PTNextV3',
		RT_PT   = 'RT+PT',
		RTOnly  = 'RT',
		RASTER  = 'Raster',
	},
	quality = {
		VANILLA = 'Vanilla',
		FAST    = 'Fast',
		MEDIUM  = 'Med',
		HIGH    = 'High',
		INSANE  = 'Insane',
		AUTO    = 'Auto',
	},
	vram = {
		OFF		= 'Off',
		GB4		= '4-8',
		GB10	= '10/12',
		GB16	= '16',
		GB20	= '20-32',
		AUTO	= 'Auto',
	},
	sharc = {
		OFF     = 'Off (AMD Pink Tracing)',
		CACHE   = 'Off (Cache Only)',
		VANILLA = 'Vanilla',
		FAST    = 'Fast',
		MEDIUM  = 'Med',
		HIGH    = 'High',
		INSANE  = 'Insane',
	},
	denoiserMode = {
		RR   = 'Ray Reconstruction',
		NRD  = 'NRD',
		NONE = 'None',
	},
	graphics = {
		POTATO  = 'Potato',
		FAST    = 'Fast',
		MEDIUM  = 'Med',
		HIGH    = 'High',
		OFF     = 'Off',
	},
	ptLightingMode = {
		VANILLA		= 'Vanilla',
		ORIGINAL	= 'PTNext Original',
		NATURAL		= 'Natural',
		BOLD		= 'Bold',
	},
	sunAngularSizes = {
		[0]  = '0.35',
		[1]  = '0.35',
		[2]  = '0.35',
		[3]  = '0.35',
		[4]  = '0.35',
		[5]  = '0.35',
		[6]  = '0.35',
		[7]  = '0.325',
		[8]  = '0.3',
		[9]  = '0.275',
		[10] = '0.25',
		[11] = '0.225',
		[12] = '0.225',
		[13] = '0.225',
		[14] = '0.225',
		[15] = '0.25',
		[16] = '0.275',
		[17] = '0.3',
		[18] = '0.3',
		[19] = '0.325',
		[20] = '0.35',
		[21] = '0.35',
		[22] = '0.35',
		[23] = '0.35',
		PreviousHour = -1,
	},
	state = {
		_isPhotoMode        = false,
		_isInElevator       = false,
		_isInVehicle        = false,
		_spatialBoostActive = false,
	},
	config = {
		BASE_SPATIAL_DI = '24.0',
		BASE_SPATIAL_GI = '24.0',
		BOOSTED_SPATIAL_DI = '24.0',
		BOOSTED_SPATIAL_GI = '32.0',
	},
}

Var.settings = {
	mode						= 'Unknown',
	modeChanged					= false,
	quality						= Var.quality.VANILLA,
	vram						= Var.vram.OFF,
	graphicsMenuOverrides		= Var.graphics.OFF,
	sharc						= Var.sharc.VANILLA,
	indoors						= nil,
	rain						= nil,
	nrdEnabled					= nil,
	showFps						= true,
	autoQualityEnabled			= false,
	autoQualityTargetFps		= 30,
	autoQualityLevel			= 3,
	autoQualityLastLevel		= 3,
	autoConfirmMenu				= true,
	restoreGraphicsMenuEnabled	= false,
	console						= false,
	tooltips					= true,
	hairAdjustments				= true,
	preemHair					= false,
	ptLightingAdjustments		= true,
	ptLightingMode				= 'Natural',	
	increaseBounceLighting      = false,
	blackBar					= true,
	theme						= 'ultraplus',
	disableSharcBlend			= true,
	transparencyFix				= true,
	denoiserMode				= nil,
	boilingFixBoost				= false,
}

return Var
